# Generated by Django 6.0.6 on 2026-07-03 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='milkShiftNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='userProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='updateMilkEntryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('liter', models.FloatField(default=50)),
                ('price', models.FloatField(default=1)),
                ('state', models.CharField(blank=True, choices=[('Present', 'Present'), ('Absent', 'Absent'), (None, None)], default=None, max_length=20, null=True)),
                ('milk_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='milkapp.milkshiftnamemodel')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milkapp.userprofilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='totalPriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_liter', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('milk_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milkapp.milkshiftnamemodel')),
                ('userprofile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='milkapp.userprofilemodel')),
            ],
        ),
        migrations.AddField(
            model_name='milkshiftnamemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_shifts_name_model', to='milkapp.userprofilemodel'),
        ),
    ]
