# Generated by Django 6.0.6 on 2026-07-03 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updatemilkentrymodel',
            old_name='profile',
            new_name='user',
        ),
    ]
