# Generated by Django 6.0.6 on 2026-07-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0002_rename_profile_updatemilkentrymodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalpricemodel',
            old_name='milk_profile',
            new_name='milk_shift',
        ),
        migrations.RenameField(
            model_name='updatemilkentrymodel',
            old_name='milk_profile',
            new_name='milk_shift',
        ),
    ]
