# Generated by Django 6.0.6 on 2026-07-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0003_rename_milk_profile_totalpricemodel_milk_shift_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='updatemilkentrymodel',
            constraint=models.UniqueConstraint(fields=('user', 'milk_shift', 'date'), name='unique_milk_entry_per_shift_date'),
        ),
    ]
